services:
  - type: web
    name: my-django-app
    env: python
    plan: free
    buildCommand: |
      apt-get update -y && \
      DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends unrar && \
      pip install -r requirements.txt
    startCommand: gunicorn your_project_name.wsgi # Assuming this is the correct command for your project
    envVars:
      - fromGroup: django-prod-env
