services:
  - type: web
    name: my-django-app
    env: python
    plan: free
    buildCommand: |
      apt-get update
      apt-get install -y unrar
      pip install -r requirements.txt
    startCommand: gunicorn your_project_name.wsgi
    envVars:
      - fromGroup: django-prod-env
